# Generated by Django 5.0.4 on 2024-06-22 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(default='')),
                ('issue_resolved', models.BooleanField(default=0)),
                ('cmr_id', models.ForeignKey(db_column='cmr_id', on_delete=django.db.models.deletion.CASCADE, to='main.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Call_Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.ForeignKey(db_column='cl_id', on_delete=django.db.models.deletion.CASCADE, to='main.calls')),
                ('reason_id', models.ForeignKey(db_column='reason_id', on_delete=django.db.models.deletion.CASCADE, to='main.reasons')),
            ],
        ),
        migrations.CreateModel(
            name='Resolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_text', models.TextField()),
                ('cl_id', models.ForeignKey(db_column='cl_id', on_delete=django.db.models.deletion.CASCADE, to='main.calls')),
            ],
        ),
    ]
